### ISSUE TITLE
Some changes that needs to be done:

### ISSUE THREAD

**Issue by Geek-ubaid** [GDGVIT/project-ideas-v2-backend#2]
Some changes that needs to be done:
- Add all compiled files of python code to gitignore (.pyc files)
- Add db.sqlite3 to gitignore
- Add .env.sample describing all the env variables
- Add comments to the code wherever required

**Comment by RiddhiGupta5** [comment]
Resolved all the issues

**Comment by Geek-ubaid** [comment]
Reference the commit here

**Comment by RiddhiGupta5** [comment]
The commit is https://github.com/GDGVIT/project-ideas-v2-backend/pull/1/commits/5bad6a42439d98637606e3d97031390b6ff307fd
